version: '3'
services:
  pet-registry-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pet-registry'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
#    expose:
#      - '3306'
    volumes:
      - pet-registry-db-vol:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  pet-registry-db-vol: {}
